version: "2"

linters:
  enable:
    - bodyclose
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    govet:
      disable:
        - shadow
    misspell:
      locale: US
  exclusions:
    rules:
      - path: "_test\\.go"
        linters:
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
  tests: false
